### ISSUE TITLE
FacetBasis outward normal vectors are false

### ISSUE THREAD

**Issue by TNBaran** [kinnala/scikit-fem#1158] opened 2024-08-08 20:16 UTC
Hello
I am new user, and I began with 8.1 version, I encountered the following issue.
FacetBasis didn't work well since upgrading to 10.0.0-3, the outward normal vectors at boundary are sometimes false.
Here an example in order to show this issue, using an annular domain, there are 2 boundaries 'Int' and 'Ext'.
In G_Vh  normal vectors are OK on two boundary 'Int' and 'Ext'
In Gm_Vh normal vectors are OK on  boundary 'Ext'
In Gu_Vh normal vectors are not OK on  boundary 'Int', this could be shown on the figure only two vectors are given on the circular boundary (red points) and in  Gu_Vh.normals.value there are only two normal vectors.
array([[[ 0.89926879,  0.89926879],
        [-0.89926879, -0.89926879],
        ........
        [ 0.89926879,  0.89926879],
        [-0.89926879, -0.89926879]],

       [[-0.43739644, -0.43739644],
        [ 0.43739644,  0.43739644],
        .......
        [-0.43739644, -0.43739644],
        [ 0.43739644,  0.43739644]]])

Here attached the mesh file created with gmsh
[Anneau01.zip](https://github.com/user-attachments/files/16552877/Anneau01.zip)

import os
print(os.environ['PATH'])
from pathlib import Path
import numpy as np
from skfem import *
from skfem.helpers import dot, grad
from skfem.io import from_meshio
import matplotlib.pyplot as plt

mesh = Mesh.load('Anneau01.msh')
element = ElementTriP1()
Vh = Basis(mesh, element)
G_Vh = FacetBasis(mesh, element)
Gm_Vh = FacetBasis(mesh, element, facets=mesh.boundaries['Ext'])
Gu_Vh = FacetBasis(mesh, element, facets=mesh.boundaries['Int'])

plt.figure(1)
plt.plot(G_Vh.normals.value[0],G_Vh.normals.value[1],'*',color='blue')
plt.plot(Gm_Vh.normals.value[0],Gm_Vh.normals.value[1],'*',color='green')
plt.plot(Gu_Vh.normals.value[0],Gu_Vh.normals.value[1],'*',color='red')
plt.show()

**Comment by kinnala** [comment] 2024-08-08 20:19
Is it fixed by 10.0.1 bugfix or a different issue?

**Comment by kinnala** [comment] 2024-08-08 20:20
This is the release from few days ago:

[10.0.1] - 2024-08-06

Fixed: Mesh.load returned incorrect orientation for some Gmsh meshes with tagged interfaces

**Comment by kinnala** [comment] 2024-08-09 11:33
It seems to be a different issue, if you do `mesh.draw(boundaries=True).show()` you can see the following:

![image](https://github.com/user-attachments/assets/83c35b7c-0679-4a35-ae45-7bdec8f6cee6)

It seems that the element associated with the internal boundary is not correct. I wonder if there is something that has been misunderstood concerning the Gmsh orientation.

**Comment by kinnala** [comment] 2024-08-09 11:35
Before this is solved, in this case the workaround is the following:
```python
mesh = MeshTri.load('Anneau01.msh', ignore_orientation=True)
```
which avoids the orientation of the boundaries according to the Gmsh logic. There is another logic in native scikit-fem meshes which assures that on exterior boundaries normal vector is always correct.

**Comment by TNBaran** [comment] 2024-08-09 14:11
Thanks,
it is OK when using this workaround.
However, there is something abnormal,  it worked fine with version 8.1 and if you examine normal vectors obtained by G_Vh = FacetBasis(mesh, element) for all boundaries, they are OK for all boundaries, so Mesh.load returned correct orientation.
I think that may be  it's facets option that's the issue.
Best regards

**Comment by kinnala** [comment] 2024-08-09 16:35
Yes, it seems that `mesh.boundaries['Int'].ori` is incorrect. This is a variable which is supposed to be inferred from the Gmsh file in `skfem.io.meshio.from_meshio`.

The value of the variable is incorrect when reading your example mesh, I will need to study in detail why this happens. There was a clear bug in `10.0.0` but as we already fixed one closely related bug in `10.0.1` there must be another one remaining.

**Comment by kinnala** [comment] 2024-08-09 16:37
I have not been able to find Gmsh documentation on the topic of normal vectors so I am just finding many of these so-called "conventions" related to the orientation of normal vectors by trial-and-error.

**Comment by kinnala** [comment] 2024-08-09 16:48
Alright, I think there is actually no remaining bug in `skfem.io.meshio.from_meshio`. It is trying to do an outward normal for a closed loop as it is supposed to do but now the issue is that the mesh has no elements inside of the closed loop, and orientation for such boundary does not make sense.

**Closed** 2024-08-09 17:15 UTC
